name: drupal9-workflows
recipe: drupal9
config:
  webroot: web
  php: '8.1'
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        PHP_IDE_CONFIG: "servername=appserver"
  drupal9-workflow:
    type: mariadb
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
  phpmyadmin:
    type: phpmyadmin
  cache:
    type: redis
