<?php

/**
 * @file
 * Provides an anonymous submission entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function d9_workflow_theme() {
  return [
    'anonymous_submission' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for anonymous submission templates.
 *
 * Default template: anonymous-submission.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the anonymous submission
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_anonymous_submission(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
